apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto
  template:
    metadata:
      labels:
        app: proyecto
    spec:
      containers:
      - name: proyecto
        image: juanpablorobayo/proyecto:v8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: proyecto
spec:
  type: LoadBalancer
  selector:
    app: proyecto
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---

